[package]
name = "protohackers"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.9"
bytes = "1.3.0"
eyre = "0.6.8"
futures = "0.3.25"
nom = "7.1.1"
primes = "0.3.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
stable-eyre = "0.2.2"
tokio = { version = "1.23.0", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[dev-dependencies]
tokio-test = "0.4.2"
