# fly.toml file generated for autumn-sound-1583 on 2023-01-01T15:36:01-08:00

app = "autumn-sound-1583"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  RUST_LOG = "info"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = 10000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
